apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: medicore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
      - name: patient-service
        image: medicore-patient-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "development"
        - name: DATABASE_URL
          value: "postgresql://neondb_owner:npg_ZnWA9KSEqO7c@ep-lingering-glitter-a1r112o9-pooler.ap-southeast-1.aws.neon.tech/patient_db?sslmode=require"
        - name: AUTH_DATABASE_URL
          value: "postgresql://neondb_owner:npg_ZnWA9KSEqO7c@ep-lingering-glitter-a1r112o9-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
        - name: DOCTOR_DATABASE_URL
          value: "postgresql://neondb_owner:npg_ZnWA9KSEqO7c@ep-lingering-glitter-a1r112o9-pooler.ap-southeast-1.aws.neon.tech/medicore_doctor?sslmode=require"
        - name: JWT_SECRET
          value: "e31203d467d0efc34b3d9c248e3c2a2e4a8345d6fee4a78a3cef8594d0a4551e94355d79da2ed4bf9021faa881a4213df017f243e5d3009518d2d6038f72df30"
        - name: CLOUDINARY_CLOUD_NAME
          value: "dvi8gecj0"
        - name: CLOUDINARY_API_KEY
          value: "665316383884714"
        - name: CLOUDINARY_API_SECRET
          value: "ePT8Gpv5Kdl_ocB5kS19X_vPz_s"
        - name: REDIS_HOST
          value: "redis.medicore.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: medicore
spec:
  selector:
    app: patient-service
  ports:
  - port: 3000
    targetPort: 3000
