apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: medicore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: medicore-payment-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "development"
        - name: DB_HOST
          value: "ep-lingering-glitter-a1r112o9-pooler.ap-southeast-1.aws.neon.tech"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "neondb"
        - name: DB_USER
          value: "neondb_owner"
        - name: DB_PASSWORD
          value: "npg_ZnWA9KSEqO7c"
        - name: DB_SSL
          value: "true"
        - name: JWT_SECRET
          value: "e31203d467d0efc34b3d9c248e3c2a2e4a8345d6fee4a78a3cef8594d0a4551e94355d79da2ed4bf9021faa881a4213df017f243e5d3009518d2d6038f72df30"
        - name: PAYMENT_GATEWAY
          value: "payhere"
        - name: PAYHERE_MERCHANT_ID
          value: "1234755"
        - name: PAYHERE_MERCHANT_SECRET
          value: "MzQ1MDM1MzI2NTM4OTQ0NDk5MzMyMDk0ODQ1NzkxMzEzMTM1OTczMw=="
        - name: PAYHERE_SANDBOX
          value: "true"
        - name: FRONTEND_URL
          value: "http://frontend.medicore.svc.cluster.local:80"
        - name: BACKEND_URL
          value: "http://api-gateway.medicore.svc.cluster.local:8080"
        - name: APPOINTMENT_SERVICE_URL
          value: "http://appointment-service.medicore.svc.cluster.local:3000"
        - name: DOCTOR_SERVICE_URL
          value: "http://doctor-service.medicore.svc.cluster.local:3000"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service.medicore.svc.cluster.local:3000"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: medicore
spec:
  selector:
    app: payment-service
  ports:
  - port: 3000
    targetPort: 3000
